server.port=${PORT:8080}

spring.thymeleaf.cache=false

spring.data.mongodb.uri=${MONGODB_URI}

gemini.api.key=${GEMINI_API_KEY}

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent